name: flutter_emoji_selector_plus
homepage: https://github.com/ahyangnb/flutter_emoji_selector_plus
issue_tracker: https://github.com/ahyangnb/flutter_emoji_selector_plus/issues
description: An Emoji picker component for Flutter with the latest set of emojis. The current version supports Emoji version 15.
repository: https://github.com/Alfaizkhan/flutter-flutter_emoji_selector_plus
version: 0.0.7

environment:
  sdk: ">=2.17.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # The state && route && data storage manage plugin.
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/flutter_emoji_selector_plus/data/emoji.json
